redis:
  app:
    host: "ai-redis-cache-vho1b2.serverless.use1.cache.amazonaws.com"
    port: 6379
    db: 0
    username: ""
    password: ""
    tls: true
    ssl_cert_reqs: "required"
    ssl_ca_certs: "/etc/ssl/certs/ca-certificates.crt"
    namespace: "app"
  worker:
    host: "ai-redis-cache-vho1b2.serverless.use1.cache.amazonaws.com"
    port: 6379
    db: 0
    username: ""
    password: ""
    tls: true
    ssl_cert_reqs: "required"
    ssl_ca_certs: "/etc/ssl/certs/ca-certificates.crt"
    namespace: "worker"
